import type { Metadata } from 'next';
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Inter } from 'next/font/google';
import './styles/globals.scss';
import { Navbar } from '@/ui/organisms/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <main className='flex min-h-screen flex-col max-w-1920 mx-auto p-4'>
            <Navbar />
            {children}
          </main>
        </body>
      </html>
     </ClerkProvider>
  );
}